package uz.project.models;

public enum ProductCategory {
    FURNITURE,
    HOME_APPLIANCE,
    TELEPHONE_AND_ACCESSORY,
    LAPTOPS_AND_DESKTOPS,
    CARPETS,
    AUDIO_APPLIANCE,
    SPORTS_EQUIPMENTS,
    GIFTS_AND_SOUVENIRS,
    KITCHEN_APPLIANCE
}
